[package]
name = "project"
version = "0.1.0"
authors = ["d.grigoriev <dmitry-gr87@yandex.ru>"]
edition = "2018"


[dependencies]
xlsxwriter = "0.2.0"
glib = "0.10.1"
gtk = { version = "0.9.1", features = ["v3_24"] }
gio = { version = "0.9.0", features = ["v2_44"] }
